# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0004_auto_20170225_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='review',
        ),
    ]
