# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0005_auto_20170225_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
